version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: simplestdb
      POSTGRES_USER: admincola
      POSTGRES_PASSWORD: ']f1V6L{>>=?wCIh>-:kw'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: simplestdb
      PGUSER: admincola
      PGPASSWORD: ']f1V6L{>>=?wCIh>-:kw'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["node", "src/app.js"]

volumes:
  pgdata: 