services:
  - type: web
    name: app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: PGHOST
        value: db
      - key: PGPORT
        value: 5432
      - key: PGDATABASE
        value: simplestdb
      - key: PGUSER
        value: admincola
      - key: PGPASSWORD
        value: ']f1V6L{>>=?wCIh>-:kw'

  - type: pserv
    name: db
    env: docker
    plan: free
    dockerCommand: |
      docker run --name db -e POSTGRES_DB=simplestdb -e POSTGRES_USER=admincola -e POSTGRES_PASSWORD=']f1V6L{>>=?wCIh>-:kw' -p 5432:5432 postgres:16
    autoDeploy: true 